### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#107]
where should we put `Dockerfile`s ?
(I have one for `centos` that builds sipi, and one that runs sipi for knora)

**Comment by subotic** [comment]
I depends ;-)

If you create dockerfiles that are customised for your deployment, then you should have a private git repository to store them.

The public general use dockerfile for Sipi is in the root of the sipi repository. Knora doesn't have one yet. The ones for GraphDB and Fuseki are in their respective folders.
