### ISSUE TITLE
Move Knora Lua config files and Lua routes to Knora repository

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#112]
Could we move all Knora specific config files and Lua scripts to the Knora repo?

If so, how do we make sure that changes to Sipi Luaserver are reflected in the scripts?

**Comment by tobiasschweizer** [comment]
Could we add the expected version of Sipi to the config file? And if we run another version of Sipi than expected, we would get a message?

**Comment by benjamingeer** [comment]
> Could we move all Knora specific config files and Lua scripts to the Knora repo?

Sure.

> Could we add the expected version of Sipi to the config file? And if we run another version of Sipi than expected, we would get a message?

Before we could do that, Sipi would need to have releases with version numbers. :)

**Comment by tobiasschweizer** [comment]
It is just because we already experienced inconsistencies between what we had in the lua scripts like log levels and the actual implementation in Sipi.

**Comment by lrosenth** [comment]
Von meinem iPhone gesendet

Am 31.01.2017 um 14:16 schrieb Tobias Schweizer <notifications@github.com<mailto:notifications@github.com>>:
Yes!!

Could we add the expected version of Sipi to the config file? And if we run another version of Sipi than expected, we would get a message

Communication!

**Comment by subotic** [comment]
resolved in #243
