### ISSUE TITLE
Add Google C++ Test Framework

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Sipi#12]
As per our discussion from today, I'm opening an issue to track the integration.

Here are some links, especially the second one describes exactly how to do it with CMake.
- Google C++ Test Framework: https://github.com/google/googletest
- Example integration in cmakeable project: https://github.com/snikulov/google-test-examples

**Comment by BiancoA** [comment]
I will open a specific branch for the integration

**Comment by subotic** [comment]
Very good, thx.

**Comment by BiancoA** [comment]
[Branch for integrating the google test Framework] (/dhlab-basel/Sipi/tree/googleTestFramework)

**Comment by BiancoA** [comment]
I think the first step for introducing google test Framework is to refactor the code, that is what I did in the branch google test framework. I will make a pull request, even if the test framework was not included, because I think that the two things should be separated.

**Comment by BiancoA** [comment]
The directory structure has been changed, now I will start adding the google test framework

**Comment by BiancoA** [comment]
on hold for now. The first line of tests script is in the branch tests/bash_scripts that will soon be merged
