### ISSUE TITLE
make sipi hostname configurable (hostname as returned by make_thumbnail)

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#124]
# description

the script `make_thumbnail.lua` returns a path where the thumbnail is accessible.
it is now hard coded:
https://github.com/dhlab-basel/Sipi/blob/develop/scripts/make_thumbnail.lua#L136

# request
can we make it configurable?

# reason
client calls sipi to upload a file and gets the url of the thumbnail
now, the url returned is always "localhost:1024"
having it configurable would help in to ease the set-up (when there is no proxy in front of sipi)

**Comment by lrosenth** [comment]
Yes, i'll look at it...

Von meinem iPhone gesendet

Am 09.02.2017 um 11:45 schrieb Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>>:

description

the script make_thumbnail.lua returns a path where the thumbnail is accessible.
it is now hard coded:
https://github.com/dhlab-basel/Sipi/blob/develop/scripts/make_thumbnail.lua#L136

request

can we make it configurable?

reason

client calls sipi to upload a file and gets the url of the thumbnail
now, the url returned is always "localhost:1024"
having it configurable would help in to ease the set-up (when there is no proxy in front of sipi)

**Comment by loicjaouen** [comment]
i'll propose an implementation shortly

**Comment by lrosenth** [comment]
😇👍

Sent from my iPad

On 9 Feb 2017, at 11:54, Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>> wrote:


i'll propose an implementation shortly

**Comment by subotic** [comment]
resolved in #125
