### ISSUE TITLE
Find thread safe alternative for Lua requests module

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#13]
The problem occurs when executing the preflight request (Lua function): each time it is called, the Lua module requests is loaded (require "requests"). This module or one of its dependencies does not seem to be thread safe.

Either we find an other Lua module to make a GET HTTP requests with cookie support, or we have to implement that ourselves in C.

We could try first these: https://luarocks.org/search?q=http

**Comment by tobiasschweizer** [comment]
https://github.com/JakobGreen/lua-requests/issues/9

**Comment by tobiasschweizer** [comment]
https://github.com/diegonehab/luasocket/issues/175

**Comment by tobiasschweizer** [comment]
`luasocket` is not thread-safe: https://github.com/diegonehab/luasocket/issues/175#issuecomment-218532459

**Comment by benjamingeer** [comment]
One option could be for Sipi to fork multiple processes instead of threads, as in Apache's [prefork](https://httpd.apache.org/docs/2.4/mod/prefork.html) mode.

**Comment by BiancoA** [comment]
solved removing luasocket
