### ISSUE TITLE
Can Sipi convert from JPEG to JPEG2000 and back to JPEG with no loss in quality?

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#146]
Hi @benjamingeer, as I see that you are working on it, can I ask what is the quality of the image we get back from sipi?

I give it a jpg and ask it back, I get the same image with the same pixel size (3008 × 2000) but neither quite the same file size (3.5M in, 700kb out) nor the quality (see screen shot).

Is it an expected behavior?

in:
![arbre](https://cloud.githubusercontent.com/assets/3933654/24269632/4fa3a0de-1012-11e7-9b09-d49f997c45fb.jpg)

out:
![arbre-retour](https://cloud.githubusercontent.com/assets/3933654/24269723/ad2dd62a-1012-11e7-8404-2df2c49f69eb.jpeg)

screenshot:
![capture d ecran 2017-03-23 a 17 25 14](https://cloud.githubusercontent.com/assets/3933654/24269818/fca7f7f8-1012-11e7-8fb1-4f7e1e7350bd.png)

you see here that there are about 20 zones where no significant signal was found and they have been averaged in color.

**Comment by benjamingeer** [comment]
It depends on what you ask Sipi for. If you ask for a JPEG, you'e going to get lossy compression, because that's how JPEGs work.

**Comment by benjamingeer** [comment]
For details of what's possible, see the IIIF Image API spec:

http://iiif.io/api/image/2.1/

**Comment by loicjaouen** [comment]
i let salsah ask ;) the request was full image, full size, color:
http://sipi-test.unil.ch/knora/6Nl274Gi0sd-GGDiZYFsl5r.jpx/full/3008,2000/0/default.jpg

it is clear that I can request it in png to get the original (except that it is now 8.7M instead of 2.5).

It is just a bit counter intuitive to upload a file in order to request it later, and not have it back, even if in this case the file is in the jpg format.

**Comment by loicjaouen** [comment]
thanks for the swift answer ;)

**Comment by benjamingeer** [comment]
OK so now I understand your question: you uploaded a JPEG, and Sipi converted int to JPEG2000 and stored it for you. Now you want the same JPEG back, with no distortion. I don't know if it's possible. We will have to ask @lrosenth.

**Comment by lrosenth** [comment]
OK, I try to answer the question. In a short: no, it is not possible! Why?

1) JPEG is a lossy compression. If You compress an image using JPEG, it always introduces artfacts (the infamous "ringing" around sharp edges). If You decompress it and compress it again using the same parameter, more artifacts are being added. Thus JPEG compression is a irreversible process with a steady degradation each time You compress/decompress the image.

2) IIIF does not give a parameter to control the compression rate. There is nothing stated in the IIIF standard, which compression rate (usually numnber between 0.0 (worst) to 1.0 (best) or 0 - 100. I think I usually use 0.8 (or 80) in SIPI. It is possible to add a URL-parameter "?quality=n" where n is a integer between 0 and 100 to control the quality in case of "../default.jpg". However, this is a SIPI-specific extension of IIIF and not standard!

Therefore it's bad practice to decompress JPEG a image and compress it again. After a few "generation" there is a very severe degradation in image quality (as You would expect in analogue copying...)

Hope this answers Your question.

**Comment by loicjaouen** [comment]
It's crystal clear, thanks Lukas.

One just has to bear in mind that sipi, for images, is not a simple media storage but an image processing engine.  
Meaning that I can have my original image back, but I won't have my original file back, because it is stored as an image and not as a file (which is only a representation and a medium).

**Comment by benjamingeer** [comment]
> It is possible to add a URL-parameter "?quality=n" where n is a integer between 0 and 100 to control the quality in case of "../default.jpg". However, this is a SIPI-specific extension of IIIF and not standard!

@lrosenth Maybe this is something we could propose to the IIIF committee?
