### ISSUE TITLE
regex to parse Knora session id is broken

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#147]
Due to the change to how the Knora session id is created, the regex in Sipi parsing the Knora session id from the cookie in the HTPP request header is broken.

Yes, I did review the change in Knora and did not notice :-)

The problem lies here (https://github.com/dhlab-basel/Sipi/blob/develop/config/sipi.init-knora.lua#L69):

```
session_id = string.match(cookie, "sid=(%d+);?")
```

As far as now, the session id was numeric. Now it contains also letter characters.

I remember that I had problems with the regex being greedy. Sometimes, the cookie header contains more stuff than the Knora session id.

**Comment by tobiasschweizer** [comment]
What about his?

`session_id = string.match(cookie, "sid=([^%s;]+)")`

Matches until it reaches a `;` or whitespace

**Comment by subotic** [comment]
resolved in #148
