### ISSUE TITLE
Could we make develop a protected branch?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#150]
In Knora, `develop` is a protected branch. With that (apart from preventing unapproved merging back to develop) comes the feature of merging `develop` directly from the github webinterface into your personal branch.

**Comment by tobiasschweizer** [comment]
https://github.com/blog/2051-protected-branches-and-required-status-checks

**Comment by benjamingeer** [comment]
Done.

**Comment by tobiasschweizer** [comment]
thx!
