### ISSUE TITLE
Sipi not using configuration variables correctly

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Sipi#163]
In the sipi configuration file, there are these two variables:

 - ``hostname``
 - ``knora_path``

In my config, I have defined ``hostname`` as ``localhost`` and ``knora_path`` as ``webapihost`` (there is an entry for ``webapihost`` inside ``/etc/hosts``).

When starting and using sipi with this configuration, I see in the log output the following errors:

```
Sipi: server.http() failed: Error #1180: HTTP GET request to http://localhost:3333/v1/files/incunabula_0000000341.jpg failed: Failed to connect to localhost port 3333: Connection refused
Sipi: server.http() failed: Error #1180: HTTP GET request to http://localhost:3333/v1/files/incunabula_0000000342.jpg failed: Failed to connect to localhost port 3333: Connection refused
Sipi: server.http() failed: Error #1180: HTTP GET request to http://localhost:3333/v1/files/incunabula_0000000340.jpg failed: Failed to connect to localhost port 3333: Connection refused
Sipi: server.http() failed: Error #1180: HTTP GET request to http://localhost:3333/v1/files/incunabula_0000000341.jpg failed: Failed to connect to localhost port 3333: Connection refused
Sipi: server.http() failed: Error #1180: HTTP GET request to http://localhost:3333/v1/files/incunabula_0000000342.jpg failed: Failed to connect to localhost port 3333: Connection refused
Sipi: GET /knora/incunabula_0000000341.jpg/full/full/0/default.jpg failed (Unauthorized): Unauthorized access
Sipi: GET /knora/incunabula_0000000341.jpg/full/full/0/default.jpg failed (Unauthorized): Unauthorized access
Sipi: GET /knora/incunabula_0000000342.jpg/full/full/0/default.jpg failed (Unauthorized): Unauthorized access
Sipi: GET /knora/incunabula_0000000342.jpg/full/full/0/default.jpg failed (Unauthorized): Unauthorized access
```

Clearly, sipi tries to connect to ``webapi`` but in doing so uses the wrong configuration variable and thus fails, since there is no ``webapi`` server running on ``localhost`` but on ``webapihost``.

Use Cases: Docker, but also any installation where ``sipi`` and ``webapi`` don't run on the same machine.

**Comment by subotic** [comment]
Not an issue anymore. I don't know what happened. Now it works as expected.

**Comment by janCstoffregen** [comment]
Liebe Leser,

Ich habe einen sehr ähnlichen Fehler: 
```
Sipi: Server.http() failed: Error #1182: HTTP GET request to http://webapihost:3333/v1/files/4BF0tu89o5V-DbH1h14Mx1g.jpg failed: Failed to connect to webapihost port 3333: No route to host
Sipi: GET /knora/4BF0tu89o5V-DbH1h14Mx1g.jpg/full/full/0/default.jpg failed (Unauthorized): Unauthorized access 
```

Ein Unterschied ist "no route to host" anstelle von "Connection refused"

webapihost ist ebenfalls in /etc/host definiert und funktioniert.

Sipi läuft als Docker Container (develop) und speichert erfolgreich die Bilder ab, die man importiert.

Die Fehlermeldung erfolgt auch mit allen möglichen authentication cookies.

Vielen Dank für eine Antwort und viele schöne Grüsse,
Jan

**Comment by subotic** [comment]
Im `sipi` Kontainer musst du die IP vom `webapi` Server eintragen. Schau mal im `.travis.yml` wie dies für die Tests gemacht wird.

**Comment by janCstoffregen** [comment]
Vielen Dank für Deine Antwort! Meinst Du hier? https://github.com/dhlab-basel/Sipi/blob/d9f804255410a93373b5ff31a03c87b72fd259f3/.travis.yml
Dort wird nur das Sipi Base erstellt, richtig?

**Comment by subotic** [comment]
Nein, hier: https://github.com/dhlab-basel/Knora/blob/develop/.travis.yml

**Comment by janCstoffregen** [comment]
ok, vielen Dank, ich seh's und probiere es jetzt!

**Comment by subotic** [comment]
Diese Zeile: `docker run -d --add-host webapihost:$DOCKERHOST -v /tmp:/tmp -v $HOME:$HOME -p 1024:1024 $SIPI_REPO:develop`

Die environment Varable `DOCKERHOST` wird weiter oben gesetzt.

**Comment by janCstoffregen** [comment]
Es funktioniert auch mit dem webapihost nicht, ich hatte Sipi schon vorher so gestartet.

**Comment by janCstoffregen** [comment]
Vielleicht hängt es mit der Firewall zusammen, auf einem Server funktioniert es und auf dem anderen nicht..

**Comment by janCstoffregen** [comment]
Es lag daran, dass der port 3333 nicht bei der firewall als geöffnet notiert ist. Dies war offensichtlich erforderlich, obwohl sich der Docker - Container auf dem gleichen Server befindet. Und auch wenn solche Dinge wie curl auf der gleichen IP funktionieren, braucht Docker dies aus irgendeinem Grund. 

Dieser Fehler tritt somit auch bei bestimmten Firewall - Konfigurationen auf. 
Gelöst mit:

```
firewall-cmd --zone=public --add-port=3333/tcp
```

Bitte entschuldigt, die Notwendigkeit, den Port zu öffnen, kannte ich nicht. Es tritt wohl gelegentlich bei Docker - Usern auf, auch im Zusammenhand mit anderer Software.
Somit kann dieses Issue wieder geschlossen werden.

Vielen Dank und viele schöne Grüsse,
Jan
