### ISSUE TITLE
Unknown field with tag 65111 (0xfe57) in converted TIFF

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#167]
When Sipi converts a TIFF image to JPEG 2000 and back again, and I try to use ImageMagick to read the TIFF, ImageMagick complains:

```
$ local/bin/sipi --file test/_test_data/images/iso-15444-4/reference_jp2/jp2_2.tif sipi_file2.jp2 --format jpx
$ local/bin/sipi --file sipi_file2.jp2 sipi_file2.tif --format tif
$ compare -metric PAE file2.tif test/_test_data/images/iso-15444-4/reference_jp2/jp2_2.tif sipi_file2.tif null:
257 (0.00392157)compare: Unknown field with tag 65111 (0xfe57) encountered. `TIFFReadDirectory' @ warning/tiff.c/TIFFWarnings/925.
```

This happens with all the test images. It seems to be something that Sipi adds, rather than something that was in the original image:

```
$ compare -metric PAE test/_test_data/images/iso-15444-4/reference_jp2/jp2_2.tif test/_test_data/images/iso-15444-4/reference_jp2/jp2_3.tif null:
44204 (0.67451)
```

**Comment by benjamingeer** [comment]
Test files are here:

http://standards.iso.org/ittf/PubliclyAvailableStandards/ISO_IEC_15444-4_2004_Conformance_Testing/reference_jp2/

**Comment by lrosenth** [comment]
Yes, I'm adding a private tag containing the original filename, the original mimetype and a checksum of the pixel data.

**Comment by benjamingeer** [comment]
OK, thanks, then I'll just ignore the warning.
