### ISSUE TITLE
Rename config options docroute and docroot to be less confusing

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#168]
The config options `docroute` and `docroot` sound the same, let's rename them.

**Comment by lrosenth** [comment]
I agree!

Von meinem iPhone gesendet

Am 15.06.2017 um 16:52 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


The config options docroute and docroot sound the same, let's rename them.
