### ISSUE TITLE
When converting on command line, get target file type from filename extension

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#169]
It's easy to forget to specify `--format`. This currently generates a JPEG 2000, but it should generate a TIFF:

```
sipi --file input.jp2 output.tif
```

**Comment by lrosenth** [comment]
We could look at the extension. May be this would be better...

Von meinem iPhone gesendet

Am 15.06.2017 um 16:57 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


It's easy to forget to specify --format. This currently generates a JPEG 2000, but it should generate a TIFF:

sipi --file input.jp2 output.tif

**Comment by lrosenth** [comment]
done
