### ISSUE TITLE
Add instructions for updating docker image for Travis

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Sipi#175]
Sipi is build on Travis inside a docker container. To add or update any software dependencies, an update to https://github.com/dhlab-basel/docker-sipi-base/blob/master/16.04/Dockerfile is needed.

To test, you can build (takes a long time) this image locally (from inside the 16.04 directory) with:
 
```
$ docker build -t dhlabbasel/sipi-base .
```

and use it to run (from inside the sipi directory) with:
 
```
$ docker run --rm -v $PWD:/sipi dhlabbasel/sipi-base /bin/sh -c “cd /sipi/build; cmake ..; make; make check”
```

After any changes are pushed to the `dhlab-basel/docker-sipi-base` repository (directly to master, no PR), docker hub should automatically start a build and published the image on https://hub.docker.com/r/dhlabbasel/sipi-base/, where Travis can access this image.

**Comment by subotic** [comment]
@benjamingeer keep me posted if this works.

**Comment by benjamingeer** [comment]
It worked, thanks!
