### ISSUE TITLE
Sipi crashes under load when requesting many IIIF-URLs with regions

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#184]
```
Jun 30 14:16:09  Sipi[65926] <Info>: GET /knora/4RwB1FEzM21-EA4X6lzfgiD.jpx/pct:38.12154696132597,28.994708994708994,18.093922651933703,8.677248677248677/pct:20/0/default.jpg: file ./images/knora/4RwB1FEzM21-EA4X6lzfgiD.jpx
Error: XMP toolkit initialization failed.
Jun 30 14:16:09  Sipi[65926] <Debug>: IIIF-Server Region:  Coordinate type: 2 | rx = 55.248619 | ry = 28.042328 | rw = 42.955803 | rh = 11.851851
Sipi Error at [/Users/tobi/gitreps/Sipi_github/src/metadata/SipiXmp.cpp: 124]: Failed to serialize XMP data!

Segmentation fault: 11
```

This happens when I request many image regions. This used to work without any problems before. Today, I built develop from scratch and now it crashes. 

```
Sipi Version 1.0 Beta (build 2017-06-30 10:57)
Sipi Source Git-Version: a82a370
```

`subdir_levels = 0`

I shared the file with you via Dropbox.

**Comment by tobiasschweizer** [comment]
This happened too:

```
Jun 30 14:35:06  Sipi[66537] <Warning>: Nothing found in cache, reading and transforming file...
Jun 30 14:35:06  Sipi[66537] <Debug>: get_size: img_w=2858 img_h=443 w=572 h=89 reduce=2 reduce only=0
Jun 30 14:35:06  Sipi[66537] <Debug>: Before writing JPG...
Jun 30 14:35:06  Sipi[66537] <Info>: Writing new cache file ./cache/cache_BAnVV9G1U0
Jun 30 14:35:06  Sipi[66537] <Debug>: Before writing JPG...
Segmentation fault: 11

```

**Comment by tobiasschweizer** [comment]
As a workaround for me, I restored the working sipi binary using the time machine

Here, everything works stable: 
```
Sipi Version 1.0 Beta (build 2017-05-10 11:30)
Sipi Source Git-Version: e0fe3b5
```

**Comment by lrosenth** [comment]
Problem recognized... XMP..
I'll solve it this weekend

Von meinem iPhone gesendet

Am 30.06.2017 um 14:36 schrieb Tobias Schweizer <notifications@github.com<mailto:notifications@github.com>>:


This happened too:

Jun 30 14:35:06  Sipi[66537] <Warning>: Nothing found in cache, reading and transforming file...
Jun 30 14:35:06  Sipi[66537] <Debug>: get_size: img_w=2858 img_h=443 w=572 h=89 reduce=2 reduce only=0
Jun 30 14:35:06  Sipi[66537] <Debug>: Before writing JPG...
Jun 30 14:35:06  Sipi[66537] <Info>: Writing new cache file ./cache/cache_BAnVV9G1U0
Jun 30 14:35:06  Sipi[66537] <Debug>: Before writing JPG...
Segmentation fault: 11

**Comment by tobiasschweizer** [comment]
strangely, I could do the same request again and it worked: GET /knora/4RwB1FEzM21-EA4X6lzfgiD.jpx/pct:38.12154696132597,28.994708994708994,18.093922651933703,8.677248677248677/pct:20/0/default.jpg

I think it happens under heavy load

**Comment by lrosenth** [comment]
Multithreading!!!

Von meinem iPhone gesendet

Am 30.06.2017 um 15:34 schrieb Tobias Schweizer <notifications@github.com<mailto:notifications@github.com>>:


strangely, I could do the same request again and it worked: GET /knora/4RwB1FEzM21-EA4X6lzfgiD.jpx/pct:38.12154696132597,28.994708994708994,18.093922651933703,8.677248677248677/pct:20/0/default.jpg

I think it happens under heavy load

**Comment by tobiasschweizer** [comment]
so between commit `e0fe3b5` and `a82a370` something was added that is not thread safe?

**Comment by tobiasschweizer** [comment]
@lrosenth and I could reproduce the problem yesterday using apache `ab` and <https://pypi.python.org/pypi/molotov>

We will try to provide a load test asap in order to detect such problems before merging changes to `develop`.
