### ISSUE TITLE
Failure in handling wrong command line options

### ISSUE THREAD

**Issue by BiancoA** [dhlab-basel/Sipi#22]
Passing a wrong option causes a segmentation fault:

```
andrea@Ubuntu-MacPro:~/Src/sipi$ build/sipi -c sipi.config.lua 
Segmentation fault (core dumped)
andrea@Ubuntu-MacPro:~/Src/sipi$ build/sipi -c 3
Segmentation fault (core dumped)
andrea@Ubuntu-MacPro:~/Src/sipi$ build/sipi -c w
Segmentation fault (core dumped)
andrea@Ubuntu-MacPro:~/Src/sipi$ build/sipi -a w
Segmentation fault (core dumped)
```

**Comment by benjamingeer** [comment]
Could be fixed by using [GNU getopt](http://www.gnu.org/software/libc/manual/html_node/Getopt.html).

**Comment by benjamingeer** [comment]
A problem with GNU getopt could be that, on Mac OS X, there is already BSD's getopt, which doesn't support long options. GNU getopt can be installed with Homebrew (`brew install gnu-getopt`), but it's not linked into `/usr/local`, to keep it from interfering with the system getopt, so I'm not sure how to get CMake to use it.

We could try this getopt implementation, which seems similar to GNU getopt but is provided as a single header file, which we could add to the  Sipi git repository:

http://optionparser.sourceforge.net/

**Comment by BiancoA** [comment]
working on it here: https://github.com/dhlab-basel/Sipi/tree/fix/comLineOptions
