### ISSUE TITLE
another strange conversion

### ISSUE THREAD

**Issue by loicjaouen** [dhlab-basel/Sipi#235]
here is a screenshot taken with `Capture` on macOS:

![capture](https://user-images.githubusercontent.com/3933654/41101258-f66735c8-6a63-11e8-8dc9-a32b558eaf4c.png)

whith the following conversion:
```bash
docker run --rm -ti -v $(pwd):/image dhlabbasel/sipi:latest /sipi/local/bin/sipi --format jpx -f /image/capture.png /image/capture-out.jpx
```

you get the following result:
![capture d ecran 2018-06-07 a 15 13 09](https://user-images.githubusercontent.com/3933654/41101808-8381936c-6a65-11e8-90dc-c3f546c99cee.png)

attaching a diff made with image magik:

```bash
docker run --rm -ti -v $(pwd):/image acleancoder/imagemagick-full:latest compare /image/capture.png /image/capture-out.jpx /image/diff.png
```

![diff](https://user-images.githubusercontent.com/3933654/41101888-b691a86e-6a65-11e8-9e1d-269cb0c2a30e.png)

**Comment by lrosenth** [comment]
Hi Loïc,

I can reproduce the error. Seems to be something wrong with writing the jpeg2000. Converting the image to a TIFF seems to be correct... I go after it ;-)

Lukas


Am 07.06.2018 um 15:16 schrieb Loïc Jaouen <notifications@github.com<mailto:notifications@github.com>>:


here is a screenshot taken with Capture on macOS:

[capture]<https://user-images.githubusercontent.com/3933654/41101258-f66735c8-6a63-11e8-8dc9-a32b558eaf4c.png>

whith the following conversion:

docker run --rm -ti -v $(pwd):/image dhlabbasel/sipi:latest /sipi/local/bin/sipi --format jpx -f /image/capture.png /image/capture-out.jpx

you get the following result:
[capture d ecran 2018-06-07 a 15 13 09]<https://user-images.githubusercontent.com/3933654/41101808-8381936c-6a65-11e8-90dc-c3f546c99cee.png>

attaching a diff made with image magik:

docker run --rm -ti -v $(pwd):/image acleancoder/imagemagick-full:latest compare /image/capture.png /image/capture-out.jpx /image/diff.png

[diff]<https://user-images.githubusercontent.com/3933654/41101888-b691a86e-6a65-11e8-9e1d-269cb0c2a30e.png>

**Comment by lrosenth** [comment]
The problem is related to the fact that the PNG contains an alpha channel (RGB + alpha).

**Comment by loicjaouen** [comment]
Thanks Lukas, I'll skip the alpha for the current imports.

**Comment by lrosenth** [comment]
@loicjaouen The bug has been fixed. It was in defining the parameters given to the kakadu compressor. Please check the branch wip/update-3rd-party-ws!
