### ISSUE TITLE
Move 3rd party scripts out of the Sipi repository

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Sipi#240]
It was decided that all 3rd party scripts (Knora, Sipiplus), should be removed from the Sipi repository.

The scripts folder will only contain documented example scripts, that should allow someone to quickly try out Sipi.

Any Sipi system-specific scripts (admin GUI, health route, etc.) providing core system functionality, will live in a separate folder.

**Comment by tobiasschweizer** [comment]
> Any Sipi system-specific scripts (admin GUI, health route, etc.) providing core system functionality, will live in a separate folder.

Shouldn't they rather be in a separate repo?
