### ISSUE TITLE
Linker warning on Mac High Sierra 10.13.6

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#278]
I get a warning from the linker on Mac High Sierra 10.13.6:

```
[100%] Linking CXX executable sipiimage
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
[100%] Built target sipiimage
```

This might be a general problem which is not specifically related to Sipi at all:

- http://sd.jtimothyking.com/2018/07/26/stub-file-and-library-file-out-of-sync/
- https://github.com/EOSIO/eos/issues/5418

Do I have to do anything about this?

**Comment by benjamingeer** [comment]
I've been seeing that warning for months. Here's how I tried to find out about it:

http://bfy.tw/LJNi

**Comment by benjamingeer** [comment]
None of the advice I found online made the error go away.

**Comment by tobiasschweizer** [comment]
This is why I put the links in 
https://github.com/dhlab-basel/Sipi/issues/278#issue-390216930

I know how to use Google ;-)

**Comment by benjamingeer** [comment]
Sorry, I'm just in a silly mood. I don't think this warning has anything to do with Sipi, I think it's an Apple compiler bug, but it seems to be harmless.

**Comment by tobiasschweizer** [comment]
>  I don't think this warning has anything to do with Sipi, I think it's an Apple compiler bug, but it seems to be harmless.

Probably you are right.

**Comment by tobiasschweizer** [comment]
@lrosenth says we can ignore it ;-)
