### ISSUE TITLE
Add in the readme - ipv4

### ISSUE THREAD

**Issue by BiancoA** [dhlab-basel/Sipi#29]
Add in the readme file the information about the only supported version of the IP: 4.

**Comment by lrosenth** [comment]
Hi Andrea,

I just added the support for IP6  and I’m am transfering the client-IP and client-portnumber to LUA into the server variable (“server.client_ip”, “server.client_port”). Please check again (sorry…). If You’re ok with it, I’ll make the merge with the develop branch and push…

Best Regards,
	Lukas

--  

Prof. Dr. Lukas Rosenthaler
Head of "Digital Humanities Lab",
University of Basel
Bernoullistrasse 32
CH-4056 Basel, Switzerland

Tel: + 41 61 267 0490
Fax: +41 61 267 3855
http://www.dhlab.unibas.ch

**Comment by BiancoA** [comment]
Dear Lukas,

I saw the changes, I think you can merge!

Bests,
Andrea
