### ISSUE TITLE
Data directory /tmp/webapi_tmp/ is not created

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#31]
After installing Sipi and trying to run it with Knora, this error occurs:

```
Knora API answered with an error:

500 Server Error: Internal Server Error
{"status":4,"error":"org.knora.webapi.FileWriteException: Data directory /tmp/webapi_tmp/ does not exist on server”}
```

Either this directory should be created by the installation process, or the README should tell the user to create it before running Sipi.

cc @sofiag

**Comment by subotic** [comment]
better yet, the existence of the  directory should be checked and if needed created by Knora/Sipi :)

**Comment by BiancoA** [comment]
Am I right if I interpret that as a user case where Sipi in used by Knora? 
It seems to me that it is not intrinsic in Sipi. If so, maybe we should start a specific documentation for Knora and Sipi together set-up

**Comment by tobiasschweizer** [comment]
yes, you are right. Ths ssue should be in Knora and not in Sipi

**Comment by subotic** [comment]
As far as I know, this is handled in Knora.
