### ISSUE TITLE
Cannot download libpng-1.6.21 during Build Process

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#32]
```
[ 45%] Performing download step (download, verify and extract) for 'project_png'
-- downloading...
     src='http://sourceforge.net/projects/libpng/files/libpng16/1.6.21/libpng-1.6.21.tar.gz/download'
     dst='/Users/tobi/gitreps/Sipi-github/build/ext/png/project_png-prefix/src/libpng-1.6.21.tar.gz'
     timeout='none'
-- [download 0% complete]
CMake Error at /Users/tobi/gitreps/Sipi-github/build/ext/png/project_png-prefix/src/project_png-stamp/download-project_png.cmake:21 (message):
  error: downloading
  'http://sourceforge.net/projects/libpng/files/libpng16/1.6.21/libpng-1.6.21.tar.gz/download'
  failed

    status_code: 22
    status_string: "HTTP response code said error"
    log:   Trying 216.34.181.60...
```

Maybe the version has to be changed to 1.6.22 or 1.6.23, see <https://sourceforge.net/projects/libpng/files/libpng16/>

**Comment by tobiasschweizer** [comment]
change link in `https://github.com/dhlab-basel/Sipi/blob/develop/ext/png/CMakeLists.txt` to <URL http://sourceforge.net/projects/libpng/files/libpng16/1.6.23/libpng-1.6.23.tar.gz/download>

**Comment by tobiasschweizer** [comment]
I hope using version 1.6.23 does not cause any compatibility problems

**Comment by BiancoA** [comment]
It should not. It was already changed in openssl branch, but we are waiting to merge it because other modification are occurring :)

**Comment by benjamingeer** [comment]
I get an error 404 (file not found) from SourceForge for libpng-1.6.21.tar.gz. Changing it to libpng-1.6.23.tar.gz works for me.

**Comment by loicjaouen** [comment]
This won't last for too long as source-forge will sooner or later move the 1.6.23 in the "older-releases" folder the same way they did for the previous ones (we already mentioned versions ranging from 1.6.20 to 1.6.23).

I suggest that we use the latest: 
https://sourceforge.net/projects/libpng/files/latest/download?source=files

So if things break it will be for a good reason (code change and not dead URL).

**Comment by lrosenth** [comment]
Good suggestion! I’ll just add it to the openssl branch!

Thanks,
Lukas

On 24 Jun 2016, at 15:06, loicjaouen <notifications@github.com<mailto:notifications@github.com>> wrote:


This won't last for too long as source-forge will sooner or later move the 1.6.23 in the "older-releases" folder the same way they did for the previous ones (we already mentioned versions ranging from 1.6.20 to 1.6.23).

I suggest that we use the latest:
https://sourceforge.net/projects/libpng/files/latest/download?source=files

So if things break it will be for a good reason (code change and not dead URL).
