### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by subotic** [dhlab-basel/Sipi#4]
If it is ok, I would like to add support for Travis-CI so that each pushed commit/pull-request automatically starts an automated build. I don't know if there are any tests, but we could then run them also.

**Comment by subotic** [comment]
@BiancoA could you please take a look at this build result: https://travis-ci.org/dhlab-basel/Sipi/builds/124506895

Am I right to assume, that simply a zip file is missing? This is probably the kakadu library, right?

**Comment by BiancoA** [comment]
@subotic you are indeed right. Kakadu library is missing, and we cannot distribute it because it has a proprietary licence. You need to find v7_8-01382N version of kakadu, you can find it in the internal git repo.

**Comment by BiancoA** [comment]
I see that you are thinking of integrating some tests: @tobiasschweizer wrote some tests in python/bash, maybe he can help

**Comment by subotic** [comment]
So, at the time being, Sipi actually cannot compile/run without Kakadu? Are there any immediate plans to make it work with a freely available JPEG-2k library?

**Comment by tobiasschweizer** [comment]
Lukas tried to make it work with openjpg <http://www.openjpeg.org/>

He said it was very slow, so it is not really feasible.

**Comment by subotic** [comment]
Ah, ok. I will then try to encrypt the kakadu zip file. Travis has the option to add encrypted files, which are then only decrypted on their server. This way, we can still run automated builds, without sharing the library on github.

**Comment by benjamingeer** [comment]
If you encrypt the zip file, won't it still be on Github, meaning that everyone will have to download a file they can't use? Would it be possible to have Travis run a script to download it from somewhere else before running the build?

**Comment by tobiasschweizer** [comment]
about testing: there is a folder `test_server` that contains some scripts that test the routes I added for Knora

**Comment by subotic** [comment]
> If you encrypt the zip file, won't it still be on Github, meaning that everyone will have to download a file they can't use? Would it be possible to have Travis run a script to download it from somewhere else before running the build?

Good question, which is what I'm pondering over for a long time now. We have the same problem in Knora and the license for Graph-DB. Basically the answer is no. We would need to supply the download link and credentials in the build-script, which can then be seen by everybody on github, and accessed this way.

As it is now, nobody can actually even build Sipi with just the content on github anyway. So adding an encrypted file and allowing automated builds is actually an improvement ;-)

I'm not really happy about it, either.

**Comment by benjamingeer** [comment]
> We would need to supply the download link and credentials in the build-script

How about encrypting the credentials?

https://docs.travis-ci.com/user/encryption-keys/

**Comment by benjamingeer** [comment]
http://stackoverflow.com/questions/9338428/using-secret-api-keys-on-travis-ci

**Comment by subotic** [comment]
and what is the difference? it is just more work. this way, I don't need to take care of storing the file on our server somewhere. one dependency less.

**Comment by subotic** [comment]
> How about encrypting the credentials?
https://docs.travis-ci.com/user/encryption-keys/

Yes, I know. This is how I encrypt the slack notification channel information.

**Comment by benjamingeer** [comment]
I'm a little worried that somehow there might be legal problems with distributing something without permission, even if we encrypt it first. I don't know.

**Comment by subotic** [comment]
ah, yes, crap. I don't really know either. But I will ask kakadu.

**Comment by subotic** [comment]
I just sent them an email. Let's see what they say.

**Comment by subotic** [comment]
I have temporarily added an encryped version of the kakadu library.

@BiancoA there seem to be another problem, as the build still fails: https://travis-ci.org/dhlab-basel/Sipi/builds/124691336 . Can you maybe take a look?

**Comment by BiancoA** [comment]
@subotic are you sure that you are using gcc > than 5.3?

**Comment by subotic** [comment]
I certainly hope so :-) It gets installed, cmake finds it and cmake is instructed directly to us it (``cmake -DCMAKE_CXX_COMPILER=g++-5``)

**Comment by BiancoA** [comment]
:) it seems to be an error with the embedded library and its dependencies, OS related so to say...

this guy had the same problem:
https://groups.yahoo.com/neo/groups/kakadu_jpeg2000/conversations/topics/7095

**Comment by subotic** [comment]
I found the error. The gcc version that was installing was 5.2, which is the highest available for Ubuntu 12.04 LTS. I changed the distribution to Ubuntu 14.04 LTS and here the 5.3 gets installed.

Isn't there a way in cmake to define the minimum required compiler version? If sipi needs gcc >= 5.3, then IMHO there should be a check at the beginning. Would have saved me a lot of time and will probably save a lot of time for others :)

It now fails somewhere else: https://travis-ci.org/dhlab-basel/Sipi/jobs/125059788

```
[ 49%] Performing build step for 'project_luarocks'
Done. Type 'make install' to install into /home/travis/build/dhlab-basel/Sipi/local.
[ 50%] Performing install step for 'project_luarocks'
mkdir: cannot create directory ‘/usr/local/luarocks’: Permission denied
make[3]: *** [write_sysconfig] Error 1
make[2]: *** [project_luarocks-prefix/src/project_luarocks-stamp/project_luarocks-install] Error 2
make[1]: *** [CMakeFiles/project_luarocks.dir/all] Error 2
make: *** [all] Error 2
```

At least the OSX build is running through :) https://travis-ci.org/dhlab-basel/Sipi/jobs/125059789

**Comment by subotic** [comment]
@tobiasschweizer The build on Travis-CI (Ubuntu Trusty) fails on the step where ``luarocks`` needs to be installed. Can you please take a look at the log: https://travis-ci.org/dhlab-basel/Sipi/jobs/125059788

At first, I thought this issue has something to do with needing to set the ``luarocks`` environment variables. But this doesn't seem to be the case, since CMake/make needs to be run first, so that those variables can be set.

There must be something other causing the problem. The build is running as a normal user. You also mentioned that you are running it under Ubuntu as a normal user, and that on your machine it is running through. So what's different then?

**Comment by tobiasschweizer** [comment]
I see. The problem is that `/usr/local/luarocks` is attempted to be created during the build. This directory is defined in `CMakeList.txt`: `--rocks-tree=${CMAKE_INSTALL_PREFIX}/luarocks` 

And this requires root rights:

```bash
mkdir: cannot create directory ‘/usr/local/luarocks’: Permission denied
```

So just create this directory using `sudo` before doing the build.

**Comment by subotic** [comment]
But is this correct? Didn't you say that ``luarocks`` should be available at ``sipi/local/luarocks`` and not at ``/usr/local/luarocks``?

**Comment by subotic** [comment]
I see now that this is the parameter for the tree ``--rocks-tree=${CMAKE_INSTALL_PREFIX}/luarocks``. Does it make sense to define the folder for the tree to be in ``/usr/local/luarocks``, when the binaries are in ``sipi/local/bin/luarocks``. Isn't it safer that the folder for the modules be inside the sipi folder? What if the user has already a bunch of lua modules installed, in versions that he wants. Is this going to be a problem for Sipi or the user? Shouldn't the sipi build be self-contained and not write into the users system folders?

**Comment by tobiasschweizer** [comment]
We are talking about two different things here:

 `local/bin/luarocks` (in SIPI-Dir) is the destination of the luarocks binary, i.e. the executable.

`usr/local/luarocks` is the lua rocks tree, i.e. the defualt destination of the Lua modules.

**Comment by subotic** [comment]
yes, that is what I wrote just now :-)

**Comment by tobiasschweizer** [comment]
:-)

**Comment by tobiasschweizer** [comment]
Please ask @lrosenth about the luarocks tree, he defined it in CMakeList.txt

**Comment by subotic** [comment]
Ok, thanks, will do :)

**Comment by subotic** [comment]
ok, almost there. Now it fails at the last step: 

```
[100%] Building CXX object CMakeFiles/sipi.dir/iiifparser/SipiSize.cpp.o
make[2]: *** No rule to make target `../local/lib/x86_64-linux-gnu/libtiff.a', needed by `sipi'.  Stop.
make[1]: *** [CMakeFiles/sipi.dir/all] Error 2
make: *** [all] Error 2
```

Here is the link to the log: https://travis-ci.org/dhlab-basel/Sipi/jobs/129059085#L6954-L6957

@lrosenth @BiancoA any suggestions?

**Comment by BiancoA** [comment]
Is `../local/lib/x86_64-linux-gnu/libtiff.a` present? because on my ubuntu it is

**Comment by subotic** [comment]
nope: https://travis-ci.org/dhlab-basel/Sipi/jobs/129116235#L7012-L7036

**Comment by BiancoA** [comment]
I checked and I found what could cause the problem: to better figure it out, I ask you to add in the CMakeList.txt file
```
MESSAGE(STATUS "Distro name: " ${CMAKE_DISTRO_NAME})
```
at line 226, and then from the build dir execute `cmake ...`, on my system the result is: 
```
...
-- Distro name: Ubuntu
...
```

**Comment by subotic** [comment]
yes, here also: https://travis-ci.org/dhlab-basel/Sipi/jobs/129362496#L403

**Comment by BiancoA** [comment]
result of `printenv`
```
NVM_RC_VERSION=
XDG_VTNR=7
LC_PAPER=de_CH.UTF-8
LC_ADDRESS=de_CH.UTF-8
XDG_SESSION_ID=c1
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/andrea
SELINUX_INIT=YES
LC_MONETARY=de_CH.UTF-8
CLUTTER_IM_MODULE=xim
COMP_WORDBREAKS= 	
"'><;|&(:
SESSION=ubuntu
GPG_AGENT_INFO=/run/user/1000/keyring-Z7FPLC/gpg:0:1
TERM=xterm
VTE_VERSION=3409
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
WINDOWID=25170047
LC_NUMERIC=de_CH.UTF-8
OLDPWD=/home/andrea/Src/google-test-examples
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1552
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-Z7FPLC
GTK_MODULES=gail:atk-bridge:canberra-gtk-module:canberra-gtk-module:overlay-scrollbar:unity-gtk-module
NVM_DIR=/home/andrea/.nvm
USER=andrea
LC_TELEPHONE=de_CH.UTF-8
LIBGL_DRIVERS_PATH=/usr/lib/fglrx/dri:/usr/lib/x86_64-linux-gnu/dri:/usr/lib/dri:/usr/lib32/fglrx/dri:/usr/lib/i386-linux-gnu/dri
LD_LIBRARY_PATH=/usr/local/lib:/usr/lib32
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring-Z7FPLC/ssh
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
SESSION_MANAGER=local/Ubuntu-MacPro:@/tmp/.ICE-unix/1727,unix/Ubuntu-MacPro:/tmp/.ICE-unix/1727
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
DESKTOP_SESSION=ubuntu
PATH=/home/andrea/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
NVM_NODEJS_ORG_MIRROR=http://nodejs.org/dist
LC_IDENTIFICATION=de_CH.UTF-8
PWD=/home/andrea/Src/google-test-examples/build
JOB=dbus
XMODIFIERS=@im=ibus
GNOME_KEYRING_PID=1681
LANG=en_US.UTF-8
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_MEASUREMENT=de_CH.UTF-8
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
GDMSESSION=ubuntu
SESSIONTYPE=gnome-session
SHLVL=1
HOME=/home/andrea
XDG_SEAT=seat0
LANGUAGE=en_US
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
MATHEMATICA_HOME=/usr/local/Wolfram/Mathematica/10.1
PYTHONPATH=/usr/share/python-support/root/:
LOGNAME=andrea
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-2cSvdxGHaG
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/
QT4_IM_MODULE=ibus
LESSOPEN=| /usr/bin/lesspipe %s
PKG_CONFIG_PATH=:/usr/local/lib/pkgconfig
INSTANCE=
TEXTDOMAIN=im-config
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=ibus
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=de_CH.UTF-8
TEXTDOMAINDIR=/usr/share/locale/
LC_NAME=de_CH.UTF-8
XAUTHORITY=/home/andrea/.Xauthority
COLORTERM=gnome-terminal
_=/usr/bin/printenv
```

**Comment by subotic** [comment]
I've added a ``Dockerfile``, which can be used to build the project inside a controlled environment. Docker needs to be installed and running (docker daemon)

From inside the ``sipi`` project folder, type:
```
$ docker build -t sipi .
$ docker run -it -rm -v "$PWD":/usr/src/sipi -w /usr/src/sipi sipi
```

Afterwords you get a prompt, which is inside the container. Then proceed as usually:
```
root@xyz:/usr/src/sipi# cd build
root@xyz:/usr/src/sipi/build# cmake ..
root@xyz:/usr/src/sipi/build# make 
```

**Comment by subotic** [comment]
Kakadu fails to compile:

```
In file included from ../kdu_jni/kdu_jni.cpp:8:0:
../kdu_jni/kdu_jni.h:11:18: fatal error: jni.h: No such file or directory
compilation terminated.
In file included from ../all_includes/kdu_servex.h:45:0,
                 from ../kdu_aux/kdu_aux.h:20,
                 from ../kdu_aux/kdu_aux.cpp:4:
../all_includes/jp2_shared.h:949:25: warning: 'kd_supp_local::jp2_brand' defined but not used [-Wunused-variable]
 static const kdu_uint32 jp2_brand           = jp2_4cc_to_int("jp2 ");
                         ^
../all_includes/jp2_shared.h:950:25: warning: 'kd_supp_local::jpx_brand' defined but not used [-Wunused-variable]
 static const kdu_uint32 jpx_brand           = jp2_4cc_to_int("jpx ");
                         ^
../all_includes/jp2_shared.h:951:25: warning: 'kd_supp_local::jpx_baseline_brand' defined but not used [-Wunused-variable]
 static const kdu_uint32 jpx_baseline_brand  = jp2_4cc_to_int("jpxb");
                         ^
../all_includes/jp2_shared.h:952:25: warning: 'kd_supp_local::mj2_brand' defined but not used [-Wunused-variable]
 static const kdu_uint32 mj2_brand           = jp2_4cc_to_int("mjp2");
                         ^
Targets.mk:67: recipe for target 'libkdu_jni.so' failed
make[4]: *** [libkdu_jni.so] Error 1
Makefile-Linux-x86-64-gcc:4: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/project_kakadu.dir/build.make:107: recipe for target 'project_kakadu-prefix/src/project_kakadu-stamp/project_kakadu-build' failed
make[2]: *** [project_kakadu-prefix/src/project_kakadu-stamp/project_kakadu-build] Error 2
CMakeFiles/Makefile2:231: recipe for target 'CMakeFiles/project_kakadu.dir/all' failed
make[1]: *** [CMakeFiles/project_kakadu.dir/all] Error 2
Makefile:117: recipe for target 'all' failed
```

**Comment by lrosenth** [comment]
kakadu requires that the Java-SDK is installed. We don't need it, but the makefiles of kakadu always build the Java interface also.... Don't know how to patch the kakadu makefiles to remove this...

**Comment by subotic** [comment]
Thanks, yes. The OpenJDK should be installed with ```apt-get -y install openjdk-7-jdk``` in the docker image. Maybe I need to set something additionally?

**Comment by subotic** [comment]
My bad. I didn't set the ``JAVA_HOME`` environment variable.

**Comment by subotic** [comment]
New problem:

```
/usr/src/sipi/lib/xz-5.2.1/build-aux/missing: line 81: aclocal-1.15: command not found
WARNING: 'aclocal-1.15' is missing on your system.
         You should only need it if you modified 'acinclude.m4' or
         'configure.ac' or m4 files included by 'configure.ac'.
         The 'aclocal' program is part of the GNU Automake package:
         <http://www.gnu.org/software/automake>
         It also requires GNU Autoconf, GNU m4 and Perl in order to run:
         <http://www.gnu.org/software/autoconf>
         <http://www.gnu.org/software/m4/>
         <http://www.perl.org/>
```

I have ``aclocale 1.14.1`` installed. Will need to install it manually.

**Comment by subotic** [comment]
Finally I got it working with docker.

I changed the Dockerfile slightly, so these are the commands now to use it:

```
$ docker build -t sipi .
$ docker run -it -rm sipi
root@xyz:/usr/src/sipi# cd build
root@xyz:/usr/src/sipi/build# cmake ..
root@xyz:/usr/src/sipi/build# make
```

**Comment by BiancoA** [comment]
Awesome!
