### ISSUE TITLE
Tests in Bash Script

### ISSUE THREAD

**Issue by BiancoA** [dhlab-basel/Sipi#45]
As a first step in building an efficient and working test environment, a set of bash script are going to be developed. Requirements:

- they shall be all be started by a single main script;
- they shall return 0 if everything went ok;
- they shall return 1 or any other number, but 0, if there is a fail;

I will start a branch and develop the first version in it
@subotic @lrosenth @tobiasschweizer

**Comment by benjamingeer** [comment]
This sounds great, but are you sure you want to do it in Bash? Every time I've written something more than 10 lines long in Bash, I've wanted to bash my head against the keyboard.

**Comment by BiancoA** [comment]
I already started, have a look here: https://github.com/dhlab-basel/Sipi/tree/tests/bash_scripts/test_server :) I thought of alternatives, but:

- C++ (google tests) just take too much time for the code that has already been written. It will be implemented as a parallel project, and tests for the new code can (will?) be written in google tests;
- Python would work too, but we may want to avoid adding another programming language to the project that already has Scala, C++, Lua
- Scala/Lua are possible alternatives? I don't know them well enough to know.

I am open to suggestion, this is just a first step to have something working.

**Comment by BiancoA** [comment]
[tests branch](https://github.com/dhlab-basel/Sipi/tree/tests/bash_scripts)

**Comment by BiancoA** [comment]
how to use the first version of the scripts:

- launch sipi with the config file sipi.test-config.lua and, in another terminal, move to the folder test_server/. From there you can launch each script, with as an argument, the PID that was assigned to sipi by the operating system (ps -C sipi), for example like this:

`bash test_png.sh 11236
`
where 11236 is the PID for this session of sipi, and look at the results.

**Comment by benjamingeer** [comment]
Having something is definitely much better than having nothing! However, I wouldn't see any problem with having another programming language in the project. I suspect Python would be easier to maintain in the long run. But since you're implementing it, I think you get to choose the language. :)

**Comment by subotic** [comment]
With Scala I could help. If you want, I could take the current E2E implementation from ```Knora/webapi``` and adapt it to Sipi.

I was also thinking about Javascript/NodeJS. We just need something with a decent test runner.

**Comment by BiancoA** [comment]
@lrosenth can you try the tests I recently uploaded? you just need to checkout the [bash_scripts](https://github.com/dhlab-basel/Sipi/tree/tests/bash_scripts) branch and run the test with:

`bash test_launcher.sh`

My next step will be to make it travis compatible
