### ISSUE TITLE
Build fails on Mac OS X

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#46]
I am trying to build Sipi on branch `develop` using Mac OS X:

```
/bin/sh: /Users/tobi/gitreps/Sipi-github/patches/Makefile-MAC-x86-all-gcc.patch: No such file or directory
make[2]: *** [ext/kakadu/project_kakadu-prefix/src/project_kakadu-stamp/project_kakadu-update] Error 1
make[1]: *** [ext/kakadu/CMakeFiles/project_kakadu.dir/all] Error 2
make: *** [all] Error 2
```

Seems to be a kakadu issue. I am using `v7_8-01382N`.

**Comment by BiancoA** [comment]
@lrosenth it seems that the file patches/Makefile-MAC-x86-all-gcc.patch is missing from the github repository

**Comment by lrosenth** [comment]
My fault – sorry….

Lukas
On 10 Aug 2016, at 16:57, Andrea Bianco <notifications@github.com<mailto:notifications@github.com>> wrote:


@lrosenth<https://github.com/lrosenth> it seems that the file patches/Makefile-MAC-x86-all-gcc.patch is missing from the github repository

**Comment by tobiasschweizer** [comment]
Could you do such changes on a different branch next time? Thx.

**Comment by lrosenth** [comment]
I **thought** I was in a different branch :-( but obviously I wasn't.... Is fixed now

**Comment by tobiasschweizer** [comment]
Thx. :-)
