### ISSUE TITLE
Build stops, says file already exists (on Mac OS X)

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#53]
I did this as instructed in the README:

```
cd build
rm -rf * ../lib ../local
cmake ..
make
```

And the build stopped with this:

```
Performing patch step for 'project_kakadu'
The next patch would create the file make/Makefile-MAC-x86-64-gcc,
which already exists!  Assume -R? [n] 
```

**Comment by benjamingeer** [comment]
After I manually delete the contents of the `extsrcs` directory, `make` works, but `make install` does not:

```
$ make install
[  6%] Built target project_kakadu
[  7%] Built target icc_profiles
[ 12%] Built target project_xz
[ 17%] Built target project_zlib
[ 22%] Built target project_jpeg
[ 27%] Built target project_jbigkit
[ 28%] Performing update step for 'project_tiff'
patching file /Users/benjamingeer/git/Sipi/extsrcs/libtiff-4.0.6/libtiff/tif_dirinfo.c
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

**Comment by benjamingeer** [comment]
If I then press `y`, `make install` completes, and the tests pass.

**Comment by benjamingeer** [comment]
With the resulting build, this works fine:

```
http://localhost:1024/knora/images_0000238760.jp2/full/full/0/default.jpg
```

But this hangs:

```
http://localhost:1024/knora/images_0000238760.jp2/full/678,457/0/default.jpg
```

**Comment by benjamingeer** [comment]
I deleted my Sipi directory, checked out the git repository again, upgraded `cmake` and everything else supplied by `brew`, and ran the build again. Again I got this:

```
$ make install
[  6%] Built target project_kakadu
[  7%] Built target icc_profiles
[ 12%] Built target project_xz
[ 17%] Built target project_zlib
[ 22%] Built target project_jpeg
[ 27%] Built target project_jbigkit
[ 28%] Performing update step for 'project_tiff'
patching file /Users/benjamingeer/git/Sipi/extsrcs/libtiff-4.0.6/libtiff/tif_dirinfo.c
Reversed (or previously applied) patch detected!  Assume -R? [n] 
```

**Comment by lrosenth** [comment]
I'll have s look at it!

Lukas

Von meinem iPhone gesendet

Am 13.09.2016 um 11:31 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


I deleted my Sipi directory, checked out the git repository again, upgraded cmake and everything else supplied by brew, and ran the build again. Again I got this:

$ make install
[  6%] Built target project_kakadu
[  7%] Built target icc_profiles
[ 12%] Built target project_xz
[ 17%] Built target project_zlib
[ 22%] Built target project_jpeg
[ 27%] Built target project_jbigkit
[ 28%] Performing update step for 'project_tiff'
patching file /Users/benjamingeer/git/Sipi/extsrcs/libtiff-4.0.6/libtiff/tif_dirinfo.c
Reversed (or previously applied) patch detected!  Assume -R? [n]

**Comment by benjamingeer** [comment]
We updated the README to say that you also have to delete the `extsrcs` directory when rebuilding, and we changed the Cmake configuration to use `PATCH_COMMAND` rather than `UPDATE_COMMAND` to patch the TIFF library. That seems to fix this problem.
