### ISSUE TITLE
build fails due to missing files

### ISSUE THREAD

**Issue by SepidehAlassi** [dhlab-basel/Sipi#58]
The version cloned from github can't build due to missing files:
vendor/v7_8-01382N.zip.ZIP.
and 
'openssl/bio.h' file not found
#include <openssl/bio.h> 
used in shttps/jwt.c

**Comment by benjamingeer** [comment]
See the info about Kakadu and OpenSSL in the README. We can give you the necessary Kakadu file tomorrow.

**Comment by tobiasschweizer** [comment]
On Linux, you have to install `openssl-devel` (`openssl` is not enough because then you do not get the required header files).
 
On Mac, you can use `brew`: `brew install openssl`.
