### ISSUE TITLE
README not clear about Adobe ICC Color profile

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#6]
The README says I have to download the Adobe ICC Color profile and install it manually, but then (under **General**) it seems to say that the build framework does this automatically so I don't have to do it. On the develop branch, it's not downloaded automatically.

**Comment by BiancoA** [comment]
now it is downloaded during the cmake and extracted during the make, it should work also on mac. This is related to issue #8

**Comment by tobiasschweizer** [comment]
Can I close this issue?

**Comment by subotic** [comment]
Probably yes, since the ICC color profiles are downloaded automatically and the user doesn't need to do anything anymore, at least as far as I know.

**Comment by lrosenth** [comment]
Yee, can be closed!
Lukas

Sent from my iPad

On 27.07.2016, at 09:27, Tobias Schweizer <notifications@github.com<mailto:notifications@github.com>> wrote:


Can I close this issue?
