### ISSUE TITLE
SIPI hangs with ab stress test

### ISSUE THREAD

**Issue by lrosenth** [dhlab-basel/Sipi#62]
This is an OS X problem.... (may be also on linux)

_From what I found out this seems to be a MacOSx problem. See the following thread for
information 
http://stackoverflow.com/questions/1216267/ab-program-freezes-after-lots-of-requests-why

This is from the above thread:

On Mac OS X the default ephemeral port range is 49152 to 65535, for a total of 16384
ports. You can check this with the sysctl command:

$ sysctl net.inet.ip.portrange.first net.inet.ip.portrange.last
net.inet.ip.portrange.first: 49152
net.inet.ip.portrange.last: 65535

Changing this configuration to start from 32768 helped
$ sudo sysctl -w net.inet.ip.portrange.first=32768
net.inet.ip.portrange.first: 49152 -> 32768

Another configuration that I changed was for default timeout
Set the default timeout to 1000ms like so:

$ sudo sysctl -w net.inet.tcp.msl=1000
net.inet.tcp.msl: 15000 -> 1000

After changing above configuration following are the results 

Server Software:  
Server Hostname:        localhost
Server Port:            4000

Document Path:          /
Document Length:        12 bytes

Concurrency Level:      1
Time taken for tests:   17.005 seconds
Complete requests:      100000
Failed requests:        0
Write errors:           0
Total transferred:      14800000 bytes
HTML transferred:       1200000 bytes
Requests per second:    5880.58 [#/sec](mean)
Time per request:       0.170 [ms](mean)
Time per request:       0.170 [ms](mean, across all concurrent requests)
Transfer rate:          849.93 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.1      0      12
Processing:     0    0   0.0      0       1
Waiting:        0    0   0.0      0       1
Total:          0    0   0.1      0      12

Percentage of the requests served within a certain time (ms)
  50%      0
  66%      0
  75%      0
  80%      0
  90%      0
  95%      0
  98%      0
  99%      0
 100%     12 (longest request)_

**Comment by tobiasschweizer** [comment]
https://github.com/dhlab-basel/Knora/issues/298

**Comment by benjamingeer** [comment]
This is OK for concurrency level 1, but there's still a problem with more concurrent requests: #84.
