### ISSUE TITLE
Eliminate extra status code

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#67]
When Sipi returns JSON in response to an HTTP request, it returns two status codes:

1. The standard HTTP status code.
2. Another status code inside the JSON.

This is confusing and error-prone, and seems redundant. There are cases where Sipi returns HTTP status 200 (OK), but the JSON contains a status code indicating an error: see https://github.com/dhlab-basel/Knora/issues/266 .

Can we get rid of the error code inside the JSON, and just use HTTP status codes?

**Comment by lrosenth** [comment]
I need some more information to locate the problem: Under what circumstances results this problem. Is it from a Lua script or SIPI intrinsics? Please indicate the URL that produces the problem!

**Comment by tobiasschweizer** [comment]
I am working on it :-)

**Comment by tobiasschweizer** [comment]
#66 reports the same issue
