### ISSUE TITLE
Which compiler should be used on Mac OS X?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#7]
I have both clang and gcc installed, but the build framework is using gcc. Is this correct?

**Comment by subotic** [comment]
I think that it uses g++-5.

**Comment by benjamingeer** [comment]
Actually now I see that it's compiling some libraries with gcc and g++, and then compiling some other things with clang. I think this could cause problems, because different C++ compilers use different C++ standard libraries by default, and you can't mix them.

The README says Sipi needs gcc >= v5.3 or clang, and it says to install xcode (containing clang) on Mac, which implies that clang is preferred on Mac.

@BiancoA

**Comment by BiancoA** [comment]
On Mac os X the preferred compiler is clang. I never tried to compile it with g++.
On linux the preferred compiler is g++ version > 5.3 .

Do you think it should be made more clear on the readme?

**Comment by benjamingeer** [comment]
If you want to use clang on Mac OS X, the build process needs to be changed, because currently it automatically uses both compilers if both are installed.

**Comment by benjamingeer** [comment]
In other words, currently some files are compiled with clang and other files are compiled with gcc. That seems risky to me. I think the build process should ensure that only one compiler is used.

**Comment by BiancoA** [comment]
you are probably right, it would be better to compile everything with clang. I suppose that you are looking at the output of the make process. The problem that I see is this: what project uses gcc to compile? sip related or external? if it is an external one i think we can do very little, maybe we can compile everything with g++ also on mac

**Comment by lrosenth** [comment]
On the mac, everything should be compiles using clang. The problem may arise if g++ is installed. I assume that some of the external libraries will "prefer" g++ if available. Wenshould forece them tu use clang on OSX (which they do if g++ is missing...)

**Comment by benjamingeer** [comment]
> what project uses gcc to compile? sipi related or external?

It's hard for me to tell from the output, but I'm guessing that all the libraries that use GNU configure automatically prefer GCC, while the Sipi code is compiled with clang. I think both Cnake and GNU configure will respect the environment variables `CC` and `CXX` if they're set, so we should just need to have the build framework set them.

**Comment by lrosenth** [comment]
I will habe a look into this. It is certainly possibe to impose the use of a specific compiler with cmake, also for subprojects using GNU configure

**Comment by benjamingeer** [comment]
You have to set the `CC` and `CXX` environment variables in your `.bashrc`: http://stackoverflow.com/a/7032021
