### ISSUE TITLE
Can we delete old unused branches?

### ISSUE THREAD

**Issue by BiancoA** [dhlab-basel/Sipi#71]
Looking at the github repository I saw that branch https://github.com/dhlab-basel/Sipi/tree/ssl  is behind of 148 commits from develop. 

@lrosenth  Can we delete it?

**Comment by benjamingeer** [comment]
I see that the `ssl` branch has been deleted, but the `jpegbug` and `cmakefile/RorD` branches are now quite old. Can they be deleted?

**Comment by subotic** [comment]
Mentioned branches were deleted. Closing issue.
