### ISSUE TITLE
Log file: what do these messages mean?

### ISSUE THREAD

**Issue by tobiasschweizer** [dhlab-basel/Sipi#72]
When using Sipi with Knora, I get the following messages in my log file:

```
[2016-10-26 08:48:02.980] [shttps-logger] [warning] Couldnt switch tu user ! You must start SIPI as root!
[2016-10-26 08:49:58.502] [shttps-logger] [error] Browser unexpectedly closed connection
[2016-10-26 08:49:58.502] [shttps-logger] [warning] Error shutdown socket! Reason: Transport endpoint is not connected
```

Why would I have to start Sipi with a root user? I should be able to run it with my local user that owns the whole Sipi dir.

The other two messages can be explained by an aborted browser request. Does this lead to a problem? This will occur very often I guess since we cannot control if the client aborts the connection at some point.

Sometimes Sipi also returns an internal server error (HTTP status code 500) **when loading all the thumbnails of a manuscript (about 400 files)**. This could be related to these messages:

```
[2016-10-26 08:42:49.336] [shttps-logger] [error] Internal Server Error!Not a JPEG file: starts with 0xff 0xe0
[2016-10-26 08:43:44.189] [shttps-logger] [error] Blocking poll failed at line: 836 ERROR: Interrupted system call
```

Sometimes I get this:

```
[2016-10-26 09:01:07.571] [shttps-logger] [error] Internal Server Error!Empty input file
```

On a separate request, Sipi serves the jpg without problems. The jpeg was also created by Sipi itself when importing it using Knora.

**Comment by benjamingeer** [comment]
> Why would I have to start Sipi with a root user?

Looking at the code, I think you only have to start Sipi as root if you want it to change to a certain user after it starts. I think you need to comment out `userid` in the config file:

```
    --
    -- user under which the sipi server should run. Don't set (comment out) this configuration variable
    -- if SIPI should use the user which launches SIPI!
    --
    userid = '_www',
```

I think this should be commented out by default. Running any software as root is a security risk.

**Comment by tobiasschweizer** [comment]
[2016-10-26 15:39:14.958] [shttps-logger] [warning] Couldnt switch tu user ! You must start SIPI as root!
[2016-10-26 15:40:27.565] [shttps-logger] [error] Internal Server Error!Not a JPEG file: starts with 0xff 0x

**Comment by lrosenth** [comment]
Perfect!! YES!!

:-)

It’s a feature,
Lukas

On 26 Oct 2016, at 09:55, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


Why would I have to start Sipi with a root user?

Looking at the code, I think you only have to start Sipi as root if you want it to change to a certain user after it starts. I think you need to comment out userid in the config file:

    --
    -- user under which the sipi server should run. Don't set (comment out) this configuration variable
    -- if SIPI should use the user which launches SIPI!
    --
    userid = '_www',


I think this should be commented out by default. Running any software as root is a security risk.

**Comment by tobiasschweizer** [comment]
possible solution to solve problem with `libjpg`: <http://carnage-melon.tom7.org/stuff/jpegsize.html>

**Comment by loicjaouen** [comment]
for info, when using the config file `config/sipi.knora-config.lua` there is no mention of `userid`, yet `sipi` wants to switch user and still writes this warning.
It still writes it even when started as root (sudo).

**Comment by loicjaouen** [comment]
in the mean time, what is the work-around? Do you sync to a previous version? If so, which commit?

**Comment by benjamingeer** [comment]
Have you tried commenting out the line with `userid` as indicated in the config file?

**Comment by loicjaouen** [comment]
@benjamingeer see two comments above, I use the knora-config that doesn't mention `userid`.

Still, as I might have missed an inclusion that links to the config that has a `userid`, I commented out all of the `userid`s and I still get the same message.

**Comment by benjamingeer** [comment]
OK, let's let Lukas have a look at this.

**Comment by benjamingeer** [comment]
@tobiasschweizer @loicjaouen Are you still getting these error messages, or can I close this issue?

**Comment by loicjaouen** [comment]
they don't show up anymore :)

**Comment by benjamingeer** [comment]
Great, thanks!
