### ISSUE TITLE
Build fails on Mac OS X (duplicate symbol)

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#8]
```
[100%] Linking CXX executable sipi
ld: warning: directory not found for option '-L/Users/benjamingeer/git/Sipi/local/lib64'
duplicate symbol _USWebCoatedSWOP_icc_len in:
    CMakeFiles/sipi.dir/metadata/SipiIcc.cpp.o
    CMakeFiles/sipi.dir/SipiImage.cpp.o
duplicate symbol _USWebCoatedSWOP_icc in:
    CMakeFiles/sipi.dir/metadata/SipiIcc.cpp.o
    CMakeFiles/sipi.dir/SipiImage.cpp.o
ld: 2 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [sipi] Error 1
make[1]: *** [CMakeFiles/sipi.dir/all] Error 2
make: *** [all] Error 2
```

I downloaded the files `AdobeRGB1998.icc` and `USWebCoatedSWOP.icc` from the Adobe web site and generated the files `AdobeRGB1998_icc.h` and `USWebCoatedSWOP_icc.h` as instructed in the README. The generated header files are not identical to the ones in the old Sipi repository on Gitlab.

**Comment by subotic** [comment]
> download Adobe ICC Color profile http://www.adobe.com/support/downloads/iccprofiles/iccprofiles_mac.html and create two headers file: ``xxd -i AdobeRGB1998.icc > AdobeRGB1998_icc.h`` and ``xxd -i USWebCoatedSWOP.icc > USWebCoatedSWOP_icc.h``

Is there a reason why these are not added to the repository? On the page the download link points to, there seems to be a version with a license allowing bundling.

**Comment by benjamingeer** [comment]
> Is there a reason why these are not added to the repository?

I don't know.

The generated header files from the old Sipi repository on Gitlab work for me. Only the header files generated by `xxd` from the download on the Adobe web site cause the build to fail.

**Comment by tobiasschweizer** [comment]
We did not want to include the header files in our rep because we actually did not author them. So we cannot claim any authorship.

**Comment by benjamingeer** [comment]
The licence allowing bundling would require us to do this:

> If you distribute the Software on a standalone or bundled basis, you will do so by first obtaining the agreement of the end user under the terms of either the Adobe End User License Agreement (“Adobe EULA”), attached as Exhibit B, or your own license agreement which (a) complies with the terms and conditions of this Agreement; (b) effectively disclaims all warranties and conditions, express or implied, on behalf of Adobe; (c) effectively excludes all liability for damages on behalf of Adobe; (d) substantially states that any provisions that differ from this Agreement are offered by you alone and not Adobe; and (e) substantially states that the Software is available from you or Adobe and informs licensees how to obtain it in a reasonable manner on or through a medium customarily used for software exchange. Any distributed Software will include the Adobe copyright notices as included in the Software provided to you by Adobe.

**Comment by subotic** [comment]
So, dose this mean, that we need to obtain an agreement from every user that accesses the Sipi server?

**Comment by benjamingeer** [comment]
:) I guess it just means every user who downloads the code.

**Comment by subotic** [comment]
Well, it says EULA (End User License Agreement ). If a developer is building a server, then he is not the End User.

Anyway, this is a question for a lawyer. I just need to find a way to get those files on Travis-CI.

**Comment by lrosenth** [comment]
There has been a problem with a modification that Andrea did. He added the unzip -f flag in order to suppress the interactive Y/N question to overwrite. But it must be "-o", -f prevented the whole download to work. I pushed the correction to the lukas branch!

Regarding the EULA, I think we're not responsible if the "end user" downloads the color profiles (using CMake) – we do not directly provide them. I would just add a note to the readme that the the user should read the appropriate files...

**Comment by subotic** [comment]
> Regarding the EULA, I think we're not responsible if the "end user" downloads the color profiles (using CMake) – we do not directly provide them. I would just add a note to the readme that the the user should read the appropriate files...

To be able to **build** and **run** Sipi, the color profiles **need** to be downloaded by hand now (pressing a button to agree to the EULA). The question is if it is enough to simply agree to the EULA? The person building and running the server is not the "end user" of the server providing a service based on the downloaded color profiles.

**Comment by subotic** [comment]
Dose running a server using the downloaded color profiles constitutes "bundling"?

**Comment by lrosenth** [comment]
I don't think so. Bundling means providing the files with Your code. The only question is if downloading it during the bild process is critical or not...

**Comment by BiancoA** [comment]
@lrosenth I think that they are now using the develop branch, that requires the icc profiles to be downloaded by hand, while the automated process is still just on the lukas branch.

@all When pushing everything on github I took the most conservative approach on every library that is not GPL compliant. 

@benjamingeer I am going to try to compile sipi on a fresh new mac to see what the problem is

**Comment by BiancoA** [comment]
@benjamingeer can you try this again from scratch? it works fine for me now.

**Comment by subotic** [comment]
OS X builds are running through on Travis-CI with OS X 10.11 and XCode 7.3.1, e.g., https://travis-ci.org/dhlab-basel/Sipi/jobs/131196034

**Comment by BiancoA** [comment]
solved some time ago
