### ISSUE TITLE
Sipi serves empty response

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#83]
Steps to reproduce:

1. Start Knora and Sipi (using `local/bin/sipi -config config/sipi.knora-test-config.lua`).
2. Visit `http://localhost:3333/v1/files/incunabula_0000003846.jpg` in a browser to ensure that Knora's Sipi route is working.
3. Visit `http://localhost:1024/knora/incunabula_0000003846.jpg/full/full/0/default.jpg` in a browser.

Sipi prints:

```
serving test image ./images/knora/Leaves.jpg
knora_url: http://localhost:3333/v1/files/incunabula_0000003846.jpg
```

But it returns no data to the browser. The browser says `ERR_EMPTY_RESPONSE`.

**Comment by tobiasschweizer** [comment]
imgroot = './test_server/images'

**Comment by benjamingeer** [comment]
Sipi's log says:

```
[2016-12-09 16-05-29] [SIPI:INFORMATIONAL] Accepted connection from: 127.0.0.1

SHTTPS-ERROR at [/Users/benjamingeer/git/Sipi/shttps/LuaServer.cpp: #2767] 
Description: LuaServer::executeLuafunction failed: [string "..."]:86: attempt to index a boolean value (global 'result')
```

**Comment by tobiasschweizer** [comment]
yes, this message indicates that there is a runtime error in the Lua script that has been excuted

**Comment by tobiasschweizer** [comment]
Could you please try again on the branch `non_image_file_support`?

**Comment by benjamingeer** [comment]
Thanks, I'll try this on Monday.

**Comment by benjamingeer** [comment]
It works, thanks!
