### ISSUE TITLE
Can we use syslog(3) instead of the custom logger?

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#86]
http://man7.org/linux/man-pages/man3/syslog.3.html

**Comment by benjamingeer** [comment]
Advantages:

* It's already thread-safe.
* It handles log rotation.
* It's a Unix standard.

**Comment by lrosenth** [comment]
Yes, good idea! I'll lok at it...

Lukas

Sent from my iPad

On 14 Dec 2016, at 22:41, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


Advantages:

  *   It's already thread-safe.
  *   It handles log rotation.
  *   It's a Unix standard.

**Comment by subotic** [comment]
What about: http://log4cpp.sourceforge.net

**Comment by BiancoA** [comment]
log4cpp was the library we were using before implementing our own. We changed in this pull request https://github.com/dhlab-basel/Sipi/pull/79 to avoid some instability in log4cpp. The library was changing between versions...

**Comment by benjamingeer** [comment]
Done in #89.
