### ISSUE TITLE
Required Lua modules should be installed during the build process

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#9]
The script `sipi.init-knora.lua` requires the Lua modules `requests` and `json`, but these are not installed by default. Since they are used in code that's part of Sipi, they should be installed by Sipi's build process.

**Comment by loicjaouen** [comment]
Here is my mac user story installing.

I guess the symptoms of Lua missing `requests` looks like this (in the sipi logs):
```
[2016-06-27 15:07:59.422] [shttps-logger] [error] Internal server error! SHTTPS-ERROR at [/Users/ljaouen/switchdrive/Code/github/SipiLoic/lib/shttps/LuaServer.cpp: 72] Description: Lua panic: ./config/sipi.init-knora.lua:41: module 'requests' not found:
        no field package.preload['requests']
        no file '/usr/local/share/lua/5.3/requests.lua'
        no file '/usr/local/share/lua/5.3/requests/init.lua'
        no file '/usr/local/lib/lua/5.3/requests.lua'
        no file '/usr/local/lib/lua/5.3/requests/init.lua'
        no file './requests.lua'
        no file './requests/init.lua'
        no file '/usr/local/lib/lua/5.3/requests.so'
        no file '/usr/local/lib/lua/5.3/loadall.so'
        no file './requests.so'
```
and the missing piece is this one: [lua-requests](https://luarocks.org/modules/jakeg/lua-requests)

While installing locally; `./local/bin/luarocks install --tree ./local/luarocks/  lua-requests`, the installer tells about dependencies:
```
Missing dependencies for lua-requests:
lbase64
xml
luasocket
luasec >= 0.5.1
lua-cjson
md5
```
and goes on with their install procedure.
At one point it fails, complaining about:
```
Error: Failed installing dependency: https://luarocks.org/luasec-0.6-1.rockspec - Could not find header file for OPENSSL
  No file openssl/ssl.h in /usr/local/include
  No file openssl/ssl.h in /usr/include
You may have to install OPENSSL in your system and/or pass OPENSSL_DIR or OPENSSL_INCDIR to the luarocks command.
Example: luarocks install luasec OPENSSL_DIR=/usr/local
```
Being on mac (10.11), there is an `openssl` installed, but no `openssl/ssl.h` to be found.
It can be installed through [homebrew](http://brew.sh/): `brew install openssl` with files located in: `/usr/local/Cellar/openssl/`.
To resume the luarocks install, within sipi top dir, do: 
`./local/bin/luarocks install --tree ./local/luarocks/ OPENSSL_DIR=/usr/local/Cellar/openssl/1.0.2g lua-requests`

(of course your version of `openssl` might be different)

**Comment by tobiasschweizer** [comment]
we should get rid of `lua-requests` anyway because it is not thread safe

Lukas is working on a C-based luaget that is exposed to the Lua interpreter on his luaget branch

**Comment by BiancoA** [comment]
solved, the C-Based luaget was written
