### ISSUE TITLE
When converting the same TIFF file twice, Sipi doesn't produce the same result

### ISSUE THREAD

**Issue by benjamingeer** [dhlab-basel/Sipi#96]
```
$ local/bin/sipi -format jpg test/_test_data/images/knora/Leaves8.tif test1.jpg
$ local/bin/sipi -format jpg test/_test_data/images/knora/Leaves8.tif test2.jpg
$ diff test1.jpg test2.jpg
Binary files test1.jpg and test2.jpg differ

$ local/bin/sipi -format png test/_test_data/images/knora/Leaves8.tif test1.png
$ local/bin/sipi -format png test/_test_data/images/knora/Leaves8.tif test2.png
$ diff test1.png test2.png
Binary files test1.png and test2.png differ
```

**Comment by lrosenth** [comment]
@benjamingeer @BiancoA Ok, I found the "problem" (which is not a problem but a feature ;-)
1. I add a sRGB color profile to all files which do not have an explicit color profile
2. The ICC-profile automatically gets a "creation date" which of course is different each time  
Therefore we cannot use a binary compare function such as tiff
i suggest to use the ImageMagick compare:

```bash
compare -verbose -metric MAE test1.jpg test2.jpg null: 2>&1
```
The result looks like this:

>test1.jpg JPEG 2591x2572 2591x2572+0+0 8-bit sRGB 376KB 0.130u 0:00.139
>test2.jpg JPEG 2591x2572 2591x2572+0+0 8-bit sRGB 376KB 0.130u 0:00.120
>Image: test1.jpg
>  Channel distortion: MAE
>    red: 0 (0)
>    green: 0 (0)
>    blue: 0 (0)
>    all: 0 (0)
>test1.jpg=> JPEG 2591x2572 2591x2572+0+0 8-bit sRGB 0.490u 0:00.500

**Comment by benjamingeer** [comment]
OK, great! I'll change the test code to do this.

**Comment by benjamingeer** [comment]
Do I just need to look for the zeroes under "Channel distortion"?

**Comment by lrosenth** [comment]
Yes!!


On 13 Jan 2017, at 15:31, Benjamin Geer <notifications@github.com<mailto:notifications@github.com>> wrote:


Do I just need to look for the zeroes under "Channel distortion"?

**Comment by benjamingeer** [comment]
If I do this with a PNG file (resulting from the JP2 -> PNG conversion), I only get this output:

```
$ compare -verbose -metric MAE /Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png /var/folders/k8/mc3q8h_92jv3gn9wm3v_jblw0000gp/T/tmpejgncab8.png
/Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png PNG 2591x2572 2591x2572+0+0 16-bit sRGB 36.38MB 0.260u 0:00.269
compare: invalid profile length `/Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png' @ warning/png.c/MagickPNGWarningHandler/1683.
compare:  `/Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png' @ error/compare.c/CompareImagesCommand/968.
```

Does this mean the conversion result is incorrect?

**Comment by benjamingeer** [comment]
Never mind, I was missing the `null:` at the end.

**Comment by lrosenth** [comment]
Hi Ben,

Within PNG there seems to be an error about the ICC profile length – I have to look into it why this happens. Seems to be PNG specific…

Keep You updated!

Thanks, best regards,
Lukas

Am 13.01.2017 um 15:58 schrieb Benjamin Geer <notifications@github.com<mailto:notifications@github.com>>:


If I do this with a PNG file (resulting from the JP2 -> PNG conversion), I only get this output:

$ compare -verbose -metric MAE /Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png /var/folders/k8/mc3q8h_92jv3gn9wm3v_jblw0000gp/T/tmpejgncab8.png
/Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png PNG 2591x2572 2591x2572+0+0 16-bit sRGB 36.38MB 0.260u 0:00.269
compare: invalid profile length `/Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png' @ warning/png.c/MagickPNGWarningHandler/1683.
compare:  `/Users/benjamingeer/git/Sipi/test/_test_data/images/knora/LeavesC.png' @ error/compare.c/CompareImagesCommand/968.


Does this mean the conversion result is incorrect?
